- name: vars preference
  hosts: local
  connection: local
  vars:
    # NAME: playlevel 
  # vars_files:
  # - course.yaml
  vars_prompt:
  # - name: NAME
  #   prompt: What is your username?
  #   private: false
  tasks:
  - name: testing variables preference
    # vars:
    #   NAME: tasks Level
    ansible.builtin.debug:
      msg: "Name: {{ NAME }}"


# Variables Preference Level
# 1. Args Or Command Level
# 2. Task Level
# 3. File Level 
# 4. Prompt Level
# 5. Play Level
# 6. Inventory Levele