- name: vars preference
  hosts: local
  connection: local
  vars:
    NAME: Playlevel 
  vars_files:
  - course.yaml
  vars.prompt:
  - name: NAME
    prompt: What is your username?
    private: false
  tasks:
  - name: testing variables preference
  vars:
    NAME: Tasks Level
    ansible.builtin.debug:
      msg: "Name: {{ NAME }}"

