- name: user creation 
  hosts: local
  connection: local
  tasks:
  - name: check the user exist or not 
    ansible.builtin.command: id dotmart
    register: user_output
    ignore_errors: true

  - name: print user_output Info
    ansible.builtin.debug:
      msg: "{{ user_output }}"

  - name: create user dotmart
    ansible.builtin.command: useradd dotmart
    when: user_output.rc != 0