- name: play level variables 
  hosts: local
  connection: local
  vars:
    COURSE: DEVOPS with AWS
    DURATION: 10Hrs
    TRAINER: Dotmart technologies 
  
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Course is {{ COURSE }}, Duration {{ DURATION }}, Trainer is: {{ TRAINER }}"

