- name: variables from prompt
  hosts: local
  connection: local
  vars_prompt:
  - name: username
    prompt: What is your username?
    private: false
  - name: password 
    prompt: What is your username?
    private: true
  tasks:
  - name: print user name and password
    ansible.builtin.debug:
      msg: "User name is: {{ username }}, Password is: {{ password }}"

